### ISSUE TITLE
indent error with pipe (`|`)?

### ISSUE THREAD

**Issue by unional** [ota-meshi/eslint-plugin-yml#151]
```yml
abc:
  def:
    - |
      some message
      some message
```

Getting this error:

```sh
error  Expected indentation of 8 spaces but found 6 spaces  yml/indent
```

Is this correct? The formatter I use one VS Code [yaml](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) format the yaml to this.

Even if I try to change it to:

```yml
abc:
  def:
    - |
        some message
        some message
```

after format, it goes back to 6 spaces.
