### ISSUE TITLE
error  Parsing error: Map keys must be unique

### ISSUE THREAD

**Issue by ulisesbocchio** [ota-meshi/eslint-plugin-yml#177]
Input:
```yml
.anchors:
  - &anchor1
    key: value
  - &anchor2
    another: prop

foo:
  bar: baz
  <<: *anchor1
  <<: *anchor2
  
```
Output:
```bash
error  Parsing error: Map keys must be unique
```
yaml parser supports this under schema options ([merge](https://eemeli.org/yaml/#parse-options)): 

But the [parserOptionsToYAMLOption](https://github.com/ota-meshi/yaml-eslint-parser/blob/3acd7d05f422b1bee2b192fb7ba96f6e8f2f5462/src/options.ts#L6) function doesn't allow for ANY extra options to be provided except for `defaultYAMLVersion`

Can you please add support for ESlint `parserOptions` passthrough directly into the `Composer` instance?
