### ISSUE TITLE
Feature request: even array indention

### ISSUE THREAD

**Issue by hudlow** [ota-meshi/eslint-plugin-yml#199]
I prefer the following indention for YAML arrays:

```yaml
parent:
  array:
  - one
  - two
```

Would it be possible to add an option to the indent rule to enforce this indention for arrays?
