### ISSUE TITLE
Extra spaces in array list when declared on single lines

### ISSUE THREAD

**Issue by mashware** [ota-meshi/eslint-plugin-yml#209]
Hello, when we have configured the spacing of 4 and we format a Yaml, extra spaces appear in the array listt, exactly 3 spaces:
```yaml
    MyController:
        arguments:
            -   '@tactician_commandbus_default'
            -   '@tactician_commandbus_query'
            -   '@translator'
            -   '@logger'
```

 I don't know if it is the desired behavior or if there is a way to define it to be with 1 spaces:
```yaml
    MyController:
        arguments:
            - '@tactician_commandbus_default'
            - '@tactician_commandbus_query'
            - '@translator'
            - '@logger'
```
I don't know if it can be configured so that it doesn't do it in these cases
