### ISSUE TITLE
Rule block-sequence-hyphen-indicator-newline

### ISSUE THREAD

**Issue by Sweetchuck** [ota-meshi/eslint-plugin-yml#243]
My expected style is the following:

* indent every key
* every key should be in a new line

**Good**
```yaml
a: 'foo'
b: 42
c:
  d: 'bar'
e:
  - 'ab'
  - 'cd'
f:
  - 'scalar'
  -
    key1: 'scalar'
```

---

**Bad**
```yaml
f:
  - 'scalar'
  - key1: 'scalar'
```
I don't like this one, because in the key path `f:1:key1` the `1:key1` part is in the same line.
It can be even more confusing when it contains a `null` value.
```yaml
f:
  - 'scalar'
  - key1:
  - 'scalar'
```

I couldn't achieve this with the currently available settings: [yml/block-sequence-hyphen-indicator-newline](https://ota-meshi.github.io/eslint-plugin-yml/rules/block-sequence-hyphen-indicator-newline.html)
