### ISSUE TITLE
New rule for explicit null values

### ISSUE THREAD

**Issue by Sweetchuck** [ota-meshi/eslint-plugin-yml#244]
There are three different ways to define a `null` value.
```yaml
one:
two: ~
three: null
```

I think it would be useful to enforce the consistency.
