### ISSUE TITLE
Incorrect fix for certain array of objects

### ISSUE THREAD

**Issue by deathemperor** [ota-meshi/eslint-plugin-yml#314]
[Playground](https://ota-meshi.github.io/eslint-plugin-yml/playground/#eJx1VE1v2zAM/Suez9VW9NANvmVYbz0U+7gFMGiJdrRSkqePJF7R/z7ajq0k7U4GH58l8pFPL6V0CsuqFMWztqoqehdi5zFsbVFYMFgV0PeEYyidbXWXPETtbDUiE2ZRjkCtbetOaFEoiNBAwDp5WsGiaL0zNdp9VWyenh4f6m+bn5uvmx8P9a/vjwtLB0fTFTXhHqkqPIIS0hmjY0S10HrnqA4Yo7ZdOLvirCLSLUY99nB/e5sZBo51ZoWquLvPyegiUP2G8vnLQkncVO+xB4+qDhEiGrSRKS1QmHTizgkZ2JYftJWUFM4afpoTp8/HAQxty60tb0qfGCirFx6GDdEnGZ0XIfXoy+rupmw5UtrPxUxIx32jFx5j8jNinYAwWCl6llgHFHhEmficJSt5GkKhJJgHGNYEQQj8c9DdehSrPTYoLHbiL3qXcaveULnk9zCwceLrteo5E70jrrzD4wIqbFLXoc8xYUSxh4ywFgJ8Fy6AuXKDpkF/mUEehdDtBfaMwzmJtOTZTbIsKJo+DheBkDuWS45aT5ddJnsYp7D2hscrGfAYPYiGFxXBjjfFJcO7QnHnXep2K5R4eJf/d+QaoCtQm975a8E1r6p/d7ra7oG0mgXvV9RznJgsDjsdMfQgVxXIsaiu5UVCqcPZ7HituBHFfvufLBYPIgymcbQizjrJjhpr04a/GCT0612u+c26EK0nTOQl4FVmOw48uyZpYqOvNPbe1CtmgNsTUx8rKSC1VzqF93wTdqDcgUG2nuamlBgfvnwMOyGM2+chL1Dc6SAaZGfimVE5kazCNgesOU5HmsQNkLaYc/yusY78FmQoQIui1ZYlGa5QtiKcO+kEu34EWVg+SlueTc7zS6UEQYNZ3hPIzsoQy4Q88Qbks8cWPdq8C0uSrSJ31+DlKA86zgyPfxI/VmLQSGpC0mjGYGGufd7HcaxuFmow9CmMO31y6OvrP4TJPFk=)

yml with error:

```yml
- kind: postgres
  name: apple
  configuration:
    connection_info:
      database_url:
        from_env: APPLE_DATABASE_URL
      isolation_level: read-committed
      pool_settings:
        connection_lifetime: 600
        max_connections: 26
        total_max_connections: 78
      use_prepared_statements: false
  tables: "!include apple/tables/tables.yaml"
```

result: incorrect yml format, notice `kind: postgres` has wrong indentation 1 space instead of 2

```yml
- configuration:
    connection_info:
      database_url:
        from_env: APPLE_DATABASE_URL
      isolation_level: read-committed
      pool_settings:
        connection_lifetime: 600
        max_connections: 26
        total_max_connections: 78
      use_prepared_statements: false
 
 kind: postgres
  name: apple
  tables: "!include apple/tables/tables.yaml"
```
