### ISSUE TITLE
How to make a rule to check the yaml content conforms to a type

### ISSUE THREAD

**Issue by MichaelJCole** [ota-meshi/eslint-plugin-yml#49]
Hi, I'd like to validate Yaml documents and your plugin looks amazing.  I took the Playground example and started working with it.

I'd like to take a document like this and validate it against a schema - preferably a typescript type:
```
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth
spec:
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: auth
```

Do you have any suggestions on how to make a set of rules like this?  Thank you!
